List<Map<String, dynamic>> quizTopics = [
  {"topic": "GK", "emoji": "🧠"},
  {"topic": "History", "emoji": "🕰️"},
  {"topic": "Geography", "emoji": "🌍"},
  {"topic": "Science", "emoji": "🔬"},
  {"topic": "Literature", "emoji": "📚"},
  {"topic": "Art", "emoji": "🎨"},
  {"topic": "Music", "emoji": "🎵"},
  {"topic": "Movies", "emoji": "🎥"},
  {"topic": "Sports", "emoji": "⚽"},
  {"topic": "Technology", "emoji": "💻"},
  {"topic": "Famous Quotes", "emoji": "💬"},
  {"topic": "Mythology", "emoji": "🏛️"},
  {"topic": "World Leaders", "emoji": "👑"},
  {"topic": "Space ", "emoji": "🌌"},
  {"topic": "Wildlife", "emoji": "🐾"},
  {"topic": "Food", "emoji": "🍽️"},
  {"topic": "Politics", "emoji": "🗳️"},
  {"topic": "Ecology", "emoji": "🌱"},
  {"topic": "Fashion", "emoji": "👗"},
  {"topic": "Psychology", "emoji": "🧠"},
  {"topic": "Mathematics", "emoji": "🧮"},
  {"topic": "Languages", "emoji": "🗣️"},
  {"topic": "Celebrities", "emoji": "🌟"},
  {"topic": "Cartoons", "emoji": "🎬"},
  {"topic": "Business", "emoji": "💼"},
  {"topic": "Inventions", "emoji": "🔍"},
  {"topic": "Cryptocurrency", "emoji": "💰"},
  {"topic": "Pop Culture", "emoji": "🎉"},
  {"topic": "Philosophy", "emoji": "🤔"},
  {"topic": "Religion", "emoji": "⛪"},
  {"topic": "Health", "emoji": "🏋️‍♀️"},
];
